[package]
name = "idk"
version = "0.1.0"
authors = ["Hícaro <hdanrlley1@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "*", features = ["derive"] }
